(function(w){
    w.music = {
        play:function(){
            if(ifCan){
                if(switch_control){
                    if(!isplay){
                        write('A0050CC700000100000000EF68',function(ret){
                            //code
                        })
                    }else{
                        write('A0050CC700000200000000EF69',function(ret){
                            //code
                        })
                    }
                }else{
                    alert('设备还未开机')
                }
            }else{
                alert('请先连接设备')
            }
        },
        before:function(){
            if(ifCan){
                if(switch_control){
                    write('A0050CC700000001000000EF68',function(ret){
                        //console.log(JSON.stringify(ret)); 
                    })
                }else{
                    alert('设备还未开机')
                }
            }else{
                alert('请先连接设备')
            }
        },
        after:function(){
            if(ifCan){
                if(switch_control){
                    write('A0050CC700000002000000EF69',function(ret){
                        //console.log(JSON.stringify(ret)); 
                    })
                }else{
                    alert('设备还未开机')
                }
            }else{
                alert('请先连接设备')
            }
        }
    }
})(window)